---
title: "Customizing Quarto reports and presentations"
subtitle: "Lecture 26"
format: revealjs
---

## Project presentations due Dec 10! 🥳 {.smaller}

-   Make sure your presentation is pushed to your GitHub repo before your lab section.

-   **All team members must take part in the presentation**

-   Deliver or play your 5-minute presentation -- you'll lose 1 point/ minute over 5.

-   Fill out feedback forms while you listen to others' presentations.

## Project write-ups due Dec 08

-   There's a good chance you'll be done with these on Monday as well

-   But you might want to improve your write-up based on inspiration from other teams' presentations and/or ideas that came up during your peer-reviews.

-   Project repos will close at 5:00pm on Wednesday, Dec 08.
    Make sure to push your final edits to GitHub.

## Expectations {.smaller}

> The goal of this project is for you to demonstrate proficiency in the techniques we have covered in this class (and beyond, if you like) and apply them to a novel dataset in a meaningful way.

::: callout-note
Beyond, if you like -- "you" is the whole team!
:::

<br>

::: callout-important
## Read more

<https://datasciaz.netlify.app/project/description.html#introduction>
:::

## Expectations {.smaller}

> The goal is not to do an exhaustive data analysis i.e., do not calculate every statistic and procedure you have learned for every variable, but rather let me know that you are proficient at asking meaningful questions and answering them with results of data analysis, that you are proficient in using Python, and that you are proficient at interpreting and presenting the results.

<br>

::: callout-important
## Read more

<https://datasciaz.netlify.app/project/description.html#introduction>
:::

## Requirements

> Focus on methods that help you begin to answer your research questions.
> You do not have to apply every statistical procedure we learned.

<br>

::: callout-important
## Read more

<https://datasciaz.netlify.app/project/description.html#introduction>
:::

## Tip {.smaller}

> Critique your own methods and provide suggestions for improving your analysis.
> Discuss issues pertaining to the reliability and validity of your data, and appropriateness of the statistical analysis.

::: callout-tip
You can critique the current research without talking about a hypothetical future research,.
:::

<br>

::: callout-important
## Read more

<https://datasciaz.netlify.app/project/description.html#introduction>
:::

## How many plots {.smaller}

> You do not need to visualize all of the data at once.
> A single high-quality visualization will receive a much higher grade than a large number of poor-quality visualizations.

::: callout-note
There is no specific, secret number of visualizations I'm expecting, the right number is the number that it takes to answer your question.
:::

<br>

::: callout-important
## Read more

<https://datasciaz.netlify.app/project/description.html#introduction>
:::

## Submission {.smaller}

> Submission of these deliverables will happen on GitHub and feedback will be provided as GitHub issues that you need to engage with and close.
> The collection of the documents in your GitHub repo will create a webpage for your project.
> To create the webpage go to VS Code, open a terminal and type `quarto publish gh-pages` or if you have published via Quarto Pubs \`quarto publish quarto-pub

<br>

::: callout-important
## Read more

<https://datasciaz.netlify.app/project/description.html#introduction>
:::

## Writeup {.smaller}

::: question
-   Is there any paper that is required as well as the presentation?
-   What is the project write up?
-   Are write ups usually around the 10 page limit?
-   Is there a recommended outline to the project?
:::

::: callout-important
## Read more

<https://datasciaz.netlify.app/project/4-writeup-presentation.html#report-components>
:::

## Grading / rubric

::: callout-important
## Read more

-   Overall: <https://datasciaz.netlify.app/project/description.html#grading-summary>

-   Write-up: <https://datasciaz.netlify.app/project/4-writeup-presentation.html#report-components>

-   Presentation: <https://datasciaz.netlify.app/project/4-writeup-presentation.html#presentation-slides>
:::

## Something else 💛 {.smaller}

::: question
I have enjoyed this semester, and I want to continue learning Python.
What classes do you recommend I take to continue my learning?
:::

-   INFO 523: Data Mining and Discovery - Python essentially for applied ML

-   INFO 521: Intro to Machine Learning - Python as a part of the ML curriculum

# Quarto demo / Code review recap

## Your project write-up with Quarto {.smaller}

-   Chunk options around what makes it in your final report: `message`, `echo`, etc.

-   Citations.

-   Finalizing your report with `echo: false`.

## Building your project website with Quarto

-   The `docs` folder.

-   Making sure your website reflects your latest changes.

-   Customizing the look of your website.

## Slides

-   **Option 1:** Make your slides not in Quarto but make sure they're available in your Quarto project website.

-   **Option 2:** Make your slides with Quarto.

# Thank you!! 🥳 {style="text-align: center;"}
